datadog:
  api_key: '1234'

miners:
  -
    name: miner1
    hostname: "127.0.0.1"

pools:
  -
    name: verters
    type: mpos
    user_id: 123
    url: https://pool.verters.com/index.php
    api_key: 1234

exchange_rates:
  -
    pair: 'VTC/BTC'